const data = {
    movies: [
        {
            id: 'm1',
            image: "https://resizing.flixster.com/fC7nU6iTRQk02tS0SDS1ylx-G34=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2QxZjE5ZDgzLTRiY2MtNDFkYS04NWQ4LTRkYzc1ZTAwNWE2NC53ZWJw",
            title: "Avengers: Endgame",
            year: 2019,
            duration: 181,
            link: "movie.html",
            review: "Avengers Endgame brings together the culmination of more than a decade of storytelling in an epic finale filled with action, heartbreak, and triumph. It honors its characters with satisfying arcs, delivers jaw-dropping battle sequences, and provides an emotionally charged goodbye to some of the most beloved heroes of our generation.",
            budget: "400M",
            revenue: "2.8B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Anthony & Joe Russo', // Added director and genre based on common knowledge
            genre: 'Action, Sci-Fi'
        },
        {
            id: 'm2',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXWnBnPN47nWvqWJAxw-vmchKc_2u1zkG6Bw&s",
            title: "Inception",
            year: 2010,
            duration: 148,
            link: "movie.html",
            review: "Inception challenges its audience with a thrilling, mind-bending heist layered in dreams within dreams. Christopher Nolan’s direction, combined with strong performances and stunning visuals, creates an unforgettable experience that keeps you questioning reality long after the credits roll. A modern sci-fi masterpiece that rewards repeat viewings.",
            budget: "160M",
            revenue: "829M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Sci-Fi, Action'
        },
        {
            id: 'm3',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfSjSWOCaw5dnDL2GT1zFd9RMCgUGw5Q2Cfg&s",
            title: "The Matrix",
            year: 1999,
            duration: 136,
            link: "movie.html",
            review: "The Matrix revolutionized science fiction cinema with its unique bullet-time effects, innovative fight choreography, and philosophical exploration of reality. Keanu Reeves delivers a memorable performance as Neo, leading a rebellion against a simulated world. Even decades later, it remains a thrilling and thought-provoking action spectacle.",
            budget: "63M",
            revenue: "466M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'The Wachowskis',
            genre: 'Sci-Fi, Action'
        },
        {
            id: 'm4',
            image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0zt0lp-O3XdL8zzdrEvyzmcl6kOwfgbv4xQ&s",
            title: "Interstellar",
            year: 2014,
            duration: 169,
            link: "movie.html",
            review: "Interstellar is a visually stunning and deeply emotional space epic that explores themes of love, time, and survival. Christopher Nolan’s ambitious storytelling, paired with breathtaking visuals and a powerful score, deliver a space adventure that resonates both scientifically and emotionally with viewers around the world.",
            budget: "165M",
            revenue: "677M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Sci-Fi, Drama'
        },
        {
            id: 'm5',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpvyijfsP4F8o9bqAZc6bxCdbAYeKc582P1A&s",
            title: "The Dark Knight",
            year: 2008,
            duration: 152,
            link: "movie.html",
            review: "The Dark Knight transcends the superhero genre, delivering an intense crime drama built on moral dilemmas and chaos. Heath Ledger’s iconic Joker performance redefined villains on screen, while Christopher Nolan’s direction crafted a gritty, memorable tale of a hero facing his greatest challenge yet.",
            budget: "185M",
            revenue: "1B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Action, Crime, Drama'
        },
        {
            id: 'm6',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnMhjRNUPGcToFFbGDcclYcuMMi_UHnJbRcQ&s",
            title: "Avatar",
            year: 2009,
            duration: 162,
            link: "movie.html",
            review: "James Cameron’s Avatar took audiences to the lush alien world of Pandora with groundbreaking visual effects and immersive 3D technology. Its familiar story is elevated by spectacular scenery and imaginative world-building, making it one of the most successful and visually stunning blockbusters ever released.",
            budget: "237M",
            revenue: "2.9B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'James Cameron',
            genre: 'Sci-Fi, Adventure'
        },
        {
            id: 'm7',
            image: "https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_.jpg",
            title: "Titanic",
            year: 1997,
            duration: 195,
            link: "movie.html",
            review: "Titanic combines breathtaking historical recreation with a heartfelt romance aboard the ill-fated ship. James Cameron’s epic storytelling, combined with iconic performances and spectacular production design, continues to captivate audiences, ensuring its place as one of the most emotionally powerful and successful films of all time.",
            budget: "200M",
            revenue: "2.2B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'James Cameron',
            genre: 'Romance, Drama'
        },
        {
            id: 'm8',
            image: "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg",
            title: "Joker",
            year: 2019,
            duration: 122,
            link: "movie.html",
            review: "Joker offers a dark and gripping origin story of Gotham’s most notorious villain. Joaquin Phoenix’s Oscar-winning performance brings chilling depth and raw power to a character study about society’s failures and a descent into madness. It is haunting, uncomfortable, and unforgettable from beginning to end.",
            budget: "55M",
            revenue: "1.1B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Todd Phillips',
            genre: 'Crime, Drama, Thriller'
        },
        {
            id: 'm9',
            image: "https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg",
            title: "Toy Story",
            year: 1995,
            duration: 81,
            link: "movie.html",
            review: "Toy Story is a groundbreaking animated film that charmed audiences with its lovable characters and imaginative tale of friendship. Pixar’s first feature film holds up with timeless storytelling and a heartfelt message about loyalty, growing up, and discovering one’s place in the world through the eyes of toys.",
            budget: "30M",
            revenue: "373M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'John Lasseter',
            genre: 'Animation, Adventure, Comedy'
        },
        {
            id: 'm10',
            image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Gladiator_%282000_film_poster%29.png/250px-Gladiator_%282000_film_poster%29.png",
            title: "Gladiator",
            year: 2000,
            duration: 155,
            link: "movie.html",
            review: "Gladiator revives the grandeur of classic historical epics with a story of betrayal, revenge, and honor. Russell Crowe’s Oscar-winning performance as Maximus, a fallen general turned gladiator, delivers a powerful and emotional journey through ancient Rome in a film filled with memorable action and stirring drama.",
            budget: "103M",
            revenue: "503M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Ridley Scott',
            genre: 'Action, Drama'
        },
        {
            id: 'm11',
            image: "https://resizing.flixster.com/fC7nU6iTRQk02tS0SDS1ylx-G34=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2QxZjE5ZDgzLTRiY2MtNDFkYS04NWQ4LTRkYzc1ZTAwNWE2NC53ZWJw",
            title: "Avengers: Endgame",
            year: 2019,
            duration: 181,
            link: "movie.html",
            review: "Avengers Endgame brings together the culmination of more than a decade of storytelling in an epic finale filled with action, heartbreak, and triumph. It honors its characters with satisfying arcs, delivers jaw-dropping battle sequences, and provides an emotionally charged goodbye to some of the most beloved heroes of our generation.",
            budget: "400M",
            revenue: "2.8B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Anthony & Joe Russo', // Added director and genre based on common knowledge
            genre: 'Action, Sci-Fi'
        },
        {
            id: 'm12',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXWnBnPN47nWvqWJAxw-vmchKc_2u1zkG6Bw&s",
            title: "Inception",
            year: 2010,
            duration: 148,
            link: "movie.html",
            review: "Inception challenges its audience with a thrilling, mind-bending heist layered in dreams within dreams. Christopher Nolan’s direction, combined with strong performances and stunning visuals, creates an unforgettable experience that keeps you questioning reality long after the credits roll. A modern sci-fi masterpiece that rewards repeat viewings.",
            budget: "160M",
            revenue: "829M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Sci-Fi, Action'
        },
        {
            id: 'm13',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfSjSWOCaw5dnDL2GT1zFd9RMCgUGw5Q2Cfg&s",
            title: "The Matrix",
            year: 1999,
            duration: 136,
            link: "movie.html",
            review: "The Matrix revolutionized science fiction cinema with its unique bullet-time effects, innovative fight choreography, and philosophical exploration of reality. Keanu Reeves delivers a memorable performance as Neo, leading a rebellion against a simulated world. Even decades later, it remains a thrilling and thought-provoking action spectacle.",
            budget: "63M",
            revenue: "466M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'The Wachowskis',
            genre: 'Sci-Fi, Action'
        },
        {
            id: 'm14',
            image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0zt0lp-O3XdL8zzdrEvyzmcl6kOwfgbv4xQ&s",
            title: "Interstellar",
            year: 2014,
            duration: 169,
            link: "movie.html",
            review: "Interstellar is a visually stunning and deeply emotional space epic that explores themes of love, time, and survival. Christopher Nolan’s ambitious storytelling, paired with breathtaking visuals and a powerful score, deliver a space adventure that resonates both scientifically and emotionally with viewers around the world.",
            budget: "165M",
            revenue: "677M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Sci-Fi, Drama'
        },
        {
            id: 'm15',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpvyijfsP4F8o9bqAZc6bxCdbAYeKc582P1A&s",
            title: "The Dark Knight",
            year: 2008,
            duration: 152,
            link: "movie.html",
            review: "The Dark Knight transcends the superhero genre, delivering an intense crime drama built on moral dilemmas and chaos. Heath Ledger’s iconic Joker performance redefined villains on screen, while Christopher Nolan’s direction crafted a gritty, memorable tale of a hero facing his greatest challenge yet.",
            budget: "185M",
            revenue: "1B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Action, Crime, Drama'
        },
        {
            id: 'm16',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnMhjRNUPGcToFFbGDcclYcuMMi_UHnJbRcQ&s",
            title: "Avatar",
            year: 2009,
            duration: 162,
            link: "movie.html",
            review: "James Cameron’s Avatar took audiences to the lush alien world of Pandora with groundbreaking visual effects and immersive 3D technology. Its familiar story is elevated by spectacular scenery and imaginative world-building, making it one of the most successful and visually stunning blockbusters ever released.",
            budget: "237M",
            revenue: "2.9B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'James Cameron',
            genre: 'Sci-Fi, Adventure'
        },
        {
            id: 'm17',
            image: "https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_.jpg",
            title: "Titanic",
            year: 1997,
            duration: 195,
            link: "movie.html",
            review: "Titanic combines breathtaking historical recreation with a heartfelt romance aboard the ill-fated ship. James Cameron’s epic storytelling, combined with iconic performances and spectacular production design, continues to captivate audiences, ensuring its place as one of the most emotionally powerful and successful films of all time.",
            budget: "200M",
            revenue: "2.2B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'James Cameron',
            genre: 'Romance, Drama'
        },
        {
            id: 'm18',
            image: "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg",
            title: "Joker",
            year: 2019,
            duration: 122,
            link: "movie.html",
            review: "Joker offers a dark and gripping origin story of Gotham’s most notorious villain. Joaquin Phoenix’s Oscar-winning performance brings chilling depth and raw power to a character study about society’s failures and a descent into madness. It is haunting, uncomfortable, and unforgettable from beginning to end.",
            budget: "55M",
            revenue: "1.1B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Todd Phillips',
            genre: 'Crime, Drama, Thriller'
        },
        {
            id: 'm19',
            image: "https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg",
            title: "Toy Story",
            year: 1995,
            duration: 81,
            link: "movie.html",
            review: "Toy Story is a groundbreaking animated film that charmed audiences with its lovable characters and imaginative tale of friendship. Pixar’s first feature film holds up with timeless storytelling and a heartfelt message about loyalty, growing up, and discovering one’s place in the world through the eyes of toys.",
            budget: "30M",
            revenue: "373M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'John Lasseter',
            genre: 'Animation, Adventure, Comedy'
        },
        {
            id: 'm20',
            image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Gladiator_%282000_film_poster%29.png/250px-Gladiator_%282000_film_poster%29.png",
            title: "Gladiator",
            year: 2000,
            duration: 155,
            link: "movie.html",
            review: "Gladiator revives the grandeur of classic historical epics with a story of betrayal, revenge, and honor. Russell Crowe’s Oscar-winning performance as Maximus, a fallen general turned gladiator, delivers a powerful and emotional journey through ancient Rome in a film filled with memorable action and stirring drama.",
            budget: "103M",
            revenue: "503M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Ridley Scott',
            genre: 'Action, Drama'
        },
        {
            id: 'm21',
            image: "https://resizing.flixster.com/fC7nU6iTRQk02tS0SDS1ylx-G34=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2QxZjE5ZDgzLTRiY2MtNDFkYS04NWQ4LTRkYzc1ZTAwNWE2NC53ZWJw",
            title: "Avengers: Endgame",
            year: 2019,
            duration: 181,
            link: "movie.html",
            review: "Avengers Endgame brings together the culmination of more than a decade of storytelling in an epic finale filled with action, heartbreak, and triumph. It honors its characters with satisfying arcs, delivers jaw-dropping battle sequences, and provides an emotionally charged goodbye to some of the most beloved heroes of our generation.",
            budget: "400M",
            revenue: "2.8B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Anthony & Joe Russo', // Added director and genre based on common knowledge
            genre: 'Action, Sci-Fi'
        },
        {
            id: 'm22',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXWnBnPN47nWvqWJAxw-vmchKc_2u1zkG6Bw&s",
            title: "Inception",
            year: 2010,
            duration: 148,
            link: "movie.html",
            review: "Inception challenges its audience with a thrilling, mind-bending heist layered in dreams within dreams. Christopher Nolan’s direction, combined with strong performances and stunning visuals, creates an unforgettable experience that keeps you questioning reality long after the credits roll. A modern sci-fi masterpiece that rewards repeat viewings.",
            budget: "160M",
            revenue: "829M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Sci-Fi, Action'
        },
        {
            id: 'm23',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfSjSWOCaw5dnDL2GT1zFd9RMCgUGw5Q2Cfg&s",
            title: "The Matrix",
            year: 1999,
            duration: 136,
            link: "movie.html",
            review: "The Matrix revolutionized science fiction cinema with its unique bullet-time effects, innovative fight choreography, and philosophical exploration of reality. Keanu Reeves delivers a memorable performance as Neo, leading a rebellion against a simulated world. Even decades later, it remains a thrilling and thought-provoking action spectacle.",
            budget: "63M",
            revenue: "466M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'The Wachowskis',
            genre: 'Sci-Fi, Action'
        },
        {
            id: 'm24',
            image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0zt0lp-O3XdL8zzdrEvyzmcl6kOwfgbv4xQ&s",
            title: "Interstellar",
            year: 2014,
            duration: 169,
            link: "movie.html",
            review: "Interstellar is a visually stunning and deeply emotional space epic that explores themes of love, time, and survival. Christopher Nolan’s ambitious storytelling, paired with breathtaking visuals and a powerful score, deliver a space adventure that resonates both scientifically and emotionally with viewers around the world.",
            budget: "165M",
            revenue: "677M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Sci-Fi, Drama'
        },
        {
            id: 'm25',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpvyijfsP4F8o9bqAZc6bxCdbAYeKc582P1A&s",
            title: "The Dark Knight",
            year: 2008,
            duration: 152,
            link: "movie.html",
            review: "The Dark Knight transcends the superhero genre, delivering an intense crime drama built on moral dilemmas and chaos. Heath Ledger’s iconic Joker performance redefined villains on screen, while Christopher Nolan’s direction crafted a gritty, memorable tale of a hero facing his greatest challenge yet.",
            budget: "185M",
            revenue: "1B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Action, Crime, Drama'
        },
        {
            id: 'm26',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnMhjRNUPGcToFFbGDcclYcuMMi_UHnJbRcQ&s",
            title: "Avatar",
            year: 2009,
            duration: 162,
            link: "movie.html",
            review: "James Cameron’s Avatar took audiences to the lush alien world of Pandora with groundbreaking visual effects and immersive 3D technology. Its familiar story is elevated by spectacular scenery and imaginative world-building, making it one of the most successful and visually stunning blockbusters ever released.",
            budget: "237M",
            revenue: "2.9B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'James Cameron',
            genre: 'Sci-Fi, Adventure'
        },
        {
            id: 'm27',
            image: "https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_.jpg",
            title: "Titanic",
            year: 1997,
            duration: 195,
            link: "movie.html",
            review: "Titanic combines breathtaking historical recreation with a heartfelt romance aboard the ill-fated ship. James Cameron’s epic storytelling, combined with iconic performances and spectacular production design, continues to captivate audiences, ensuring its place as one of the most emotionally powerful and successful films of all time.",
            budget: "200M",
            revenue: "2.2B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'James Cameron',
            genre: 'Romance, Drama'
        },
        {
            id: 'm28',
            image: "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg",
            title: "Joker",
            year: 2019,
            duration: 122,
            link: "movie.html",
            review: "Joker offers a dark and gripping origin story of Gotham’s most notorious villain. Joaquin Phoenix’s Oscar-winning performance brings chilling depth and raw power to a character study about society’s failures and a descent into madness. It is haunting, uncomfortable, and unforgettable from beginning to end.",
            budget: "55M",
            revenue: "1.1B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Todd Phillips',
            genre: 'Crime, Drama, Thriller'
        },
        {
            id: 'm29',
            image: "https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg",
            title: "Toy Story",
            year: 1995,
            duration: 81,
            link: "movie.html",
            review: "Toy Story is a groundbreaking animated film that charmed audiences with its lovable characters and imaginative tale of friendship. Pixar’s first feature film holds up with timeless storytelling and a heartfelt message about loyalty, growing up, and discovering one’s place in the world through the eyes of toys.",
            budget: "30M",
            revenue: "373M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'John Lasseter',
            genre: 'Animation, Adventure, Comedy'
        },
        {
            id: 'm30',
            image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Gladiator_%282000_film_poster%29.png/250px-Gladiator_%282000_film_poster%29.png",
            title: "Gladiator",
            year: 2000,
            duration: 155,
            link: "movie.html",
            review: "Gladiator revives the grandeur of classic historical epics with a story of betrayal, revenge, and honor. Russell Crowe’s Oscar-winning performance as Maximus, a fallen general turned gladiator, delivers a powerful and emotional journey through ancient Rome in a film filled with memorable action and stirring drama.",
            budget: "103M",
            revenue: "503M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Ridley Scott',
            genre: 'Action, Drama'
        },
        {
            id: 'm31',
            image: "https://resizing.flixster.com/fC7nU6iTRQk02tS0SDS1ylx-G34=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2QxZjE5ZDgzLTRiY2MtNDFkYS04NWQ4LTRkYzc1ZTAwNWE2NC53ZWJw",
            title: "Avengers: Endgame",
            year: 2019,
            duration: 181,
            link: "movie.html",
            review: "Avengers Endgame brings together the culmination of more than a decade of storytelling in an epic finale filled with action, heartbreak, and triumph. It honors its characters with satisfying arcs, delivers jaw-dropping battle sequences, and provides an emotionally charged goodbye to some of the most beloved heroes of our generation.",
            budget: "400M",
            revenue: "2.8B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Anthony & Joe Russo', // Added director and genre based on common knowledge
            genre: 'Action, Sci-Fi'
        },
        {
            id: 'm32',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXWnBnPN47nWvqWJAxw-vmchKc_2u1zkG6Bw&s",
            title: "Inception",
            year: 2010,
            duration: 148,
            link: "movie.html",
            review: "Inception challenges its audience with a thrilling, mind-bending heist layered in dreams within dreams. Christopher Nolan’s direction, combined with strong performances and stunning visuals, creates an unforgettable experience that keeps you questioning reality long after the credits roll. A modern sci-fi masterpiece that rewards repeat viewings.",
            budget: "160M",
            revenue: "829M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Sci-Fi, Action'
        },
        {
            id: 'm33',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfSjSWOCaw5dnDL2GT1zFd9RMCgUGw5Q2Cfg&s",
            title: "The Matrix",
            year: 1999,
            duration: 136,
            link: "movie.html",
            review: "The Matrix revolutionized science fiction cinema with its unique bullet-time effects, innovative fight choreography, and philosophical exploration of reality. Keanu Reeves delivers a memorable performance as Neo, leading a rebellion against a simulated world. Even decades later, it remains a thrilling and thought-provoking action spectacle.",
            budget: "63M",
            revenue: "466M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'The Wachowskis',
            genre: 'Sci-Fi, Action'
        },
        {
            id: 'm34',
            image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0zt0lp-O3XdL8zzdrEvyzmcl6kOwfgbv4xQ&s",
            title: "Interstellar",
            year: 2014,
            duration: 169,
            link: "movie.html",
            review: "Interstellar is a visually stunning and deeply emotional space epic that explores themes of love, time, and survival. Christopher Nolan’s ambitious storytelling, paired with breathtaking visuals and a powerful score, deliver a space adventure that resonates both scientifically and emotionally with viewers around the world.",
            budget: "165M",
            revenue: "677M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Sci-Fi, Drama'
        },
        {
            id: 'm35',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpvyijfsP4F8o9bqAZc6bxCdbAYeKc582P1A&s",
            title: "The Dark Knight",
            year: 2008,
            duration: 152,
            link: "movie.html",
            review: "The Dark Knight transcends the superhero genre, delivering an intense crime drama built on moral dilemmas and chaos. Heath Ledger’s iconic Joker performance redefined villains on screen, while Christopher Nolan’s direction crafted a gritty, memorable tale of a hero facing his greatest challenge yet.",
            budget: "185M",
            revenue: "1B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Action, Crime, Drama'
        },
        {
            id: 'm36',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnMhjRNUPGcToFFbGDcclYcuMMi_UHnJbRcQ&s",
            title: "Avatar",
            year: 2009,
            duration: 162,
            link: "movie.html",
            review: "James Cameron’s Avatar took audiences to the lush alien world of Pandora with groundbreaking visual effects and immersive 3D technology. Its familiar story is elevated by spectacular scenery and imaginative world-building, making it one of the most successful and visually stunning blockbusters ever released.",
            budget: "237M",
            revenue: "2.9B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'James Cameron',
            genre: 'Sci-Fi, Adventure'
        },
        {
            id: 'm37',
            image: "https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_.jpg",
            title: "Titanic",
            year: 1997,
            duration: 195,
            link: "movie.html",
            review: "Titanic combines breathtaking historical recreation with a heartfelt romance aboard the ill-fated ship. James Cameron’s epic storytelling, combined with iconic performances and spectacular production design, continues to captivate audiences, ensuring its place as one of the most emotionally powerful and successful films of all time.",
            budget: "200M",
            revenue: "2.2B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'James Cameron',
            genre: 'Romance, Drama'
        },
        {
            id: 'm38',
            image: "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg",
            title: "Joker",
            year: 2019,
            duration: 122,
            link: "movie.html",
            review: "Joker offers a dark and gripping origin story of Gotham’s most notorious villain. Joaquin Phoenix’s Oscar-winning performance brings chilling depth and raw power to a character study about society’s failures and a descent into madness. It is haunting, uncomfortable, and unforgettable from beginning to end.",
            budget: "55M",
            revenue: "1.1B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Todd Phillips',
            genre: 'Crime, Drama, Thriller'
        },
        {
            id: 'm39',
            image: "https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg",
            title: "Toy Story",
            year: 1995,
            duration: 81,
            link: "movie.html",
            review: "Toy Story is a groundbreaking animated film that charmed audiences with its lovable characters and imaginative tale of friendship. Pixar’s first feature film holds up with timeless storytelling and a heartfelt message about loyalty, growing up, and discovering one’s place in the world through the eyes of toys.",
            budget: "30M",
            revenue: "373M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'John Lasseter',
            genre: 'Animation, Adventure, Comedy'
        },
        {
            id: 'm40',
            image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Gladiator_%282000_film_poster%29.png/250px-Gladiator_%282000_film_poster%29.png",
            title: "Gladiator",
            year: 2000,
            duration: 155,
            link: "movie.html",
            review: "Gladiator revives the grandeur of classic historical epics with a story of betrayal, revenge, and honor. Russell Crowe’s Oscar-winning performance as Maximus, a fallen general turned gladiator, delivers a powerful and emotional journey through ancient Rome in a film filled with memorable action and stirring drama.",
            budget: "103M",
            revenue: "503M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Ridley Scott',
            genre: 'Action, Drama'
        },{
            id: 'm41',
            image: "https://resizing.flixster.com/fC7nU6iTRQk02tS0SDS1ylx-G34=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2QxZjE5ZDgzLTRiY2MtNDFkYS04NWQ4LTRkYzc1ZTAwNWE2NC53ZWJw",
            title: "Avengers: Endgame",
            year: 2019,
            duration: 181,
            link: "movie.html",
            review: "Avengers Endgame brings together the culmination of more than a decade of storytelling in an epic finale filled with action, heartbreak, and triumph. It honors its characters with satisfying arcs, delivers jaw-dropping battle sequences, and provides an emotionally charged goodbye to some of the most beloved heroes of our generation.",
            budget: "400M",
            revenue: "2.8B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Anthony & Joe Russo', // Added director and genre based on common knowledge
            genre: 'Action, Sci-Fi'
        },
        {
            id: 'm42',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXWnBnPN47nWvqWJAxw-vmchKc_2u1zkG6Bw&s",
            title: "Inception",
            year: 2010,
            duration: 148,
            link: "movie.html",
            review: "Inception challenges its audience with a thrilling, mind-bending heist layered in dreams within dreams. Christopher Nolan’s direction, combined with strong performances and stunning visuals, creates an unforgettable experience that keeps you questioning reality long after the credits roll. A modern sci-fi masterpiece that rewards repeat viewings.",
            budget: "160M",
            revenue: "829M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Sci-Fi, Action'
        },
        {
            id: 'm43',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfSjSWOCaw5dnDL2GT1zFd9RMCgUGw5Q2Cfg&s",
            title: "The Matrix",
            year: 1999,
            duration: 136,
            link: "movie.html",
            review: "The Matrix revolutionized science fiction cinema with its unique bullet-time effects, innovative fight choreography, and philosophical exploration of reality. Keanu Reeves delivers a memorable performance as Neo, leading a rebellion against a simulated world. Even decades later, it remains a thrilling and thought-provoking action spectacle.",
            budget: "63M",
            revenue: "466M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'The Wachowskis',
            genre: 'Sci-Fi, Action'
        },
        {
            id: 'm44',
            image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0zt0lp-O3XdL8zzdrEvyzmcl6kOwfgbv4xQ&s",
            title: "Interstellar",
            year: 2014,
            duration: 169,
            link: "movie.html",
            review: "Interstellar is a visually stunning and deeply emotional space epic that explores themes of love, time, and survival. Christopher Nolan’s ambitious storytelling, paired with breathtaking visuals and a powerful score, deliver a space adventure that resonates both scientifically and emotionally with viewers around the world.",
            budget: "165M",
            revenue: "677M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Sci-Fi, Drama'
        },
        {
            id: 'm45',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpvyijfsP4F8o9bqAZc6bxCdbAYeKc582P1A&s",
            title: "The Dark Knight",
            year: 2008,
            duration: 152,
            link: "movie.html",
            review: "The Dark Knight transcends the superhero genre, delivering an intense crime drama built on moral dilemmas and chaos. Heath Ledger’s iconic Joker performance redefined villains on screen, while Christopher Nolan’s direction crafted a gritty, memorable tale of a hero facing his greatest challenge yet.",
            budget: "185M",
            revenue: "1B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Christopher Nolan',
            genre: 'Action, Crime, Drama'
        },
        {
            id: 'm46',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnMhjRNUPGcToFFbGDcclYcuMMi_UHnJbRcQ&s",
            title: "Avatar",
            year: 2009,
            duration: 162,
            link: "movie.html",
            review: "James Cameron’s Avatar took audiences to the lush alien world of Pandora with groundbreaking visual effects and immersive 3D technology. Its familiar story is elevated by spectacular scenery and imaginative world-building, making it one of the most successful and visually stunning blockbusters ever released.",
            budget: "237M",
            revenue: "2.9B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'James Cameron',
            genre: 'Sci-Fi, Adventure'
        },
        {
            id: 'm47',
            image: "https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_.jpg",
            title: "Titanic",
            year: 1997,
            duration: 195,
            link: "movie.html",
            review: "Titanic combines breathtaking historical recreation with a heartfelt romance aboard the ill-fated ship. James Cameron’s epic storytelling, combined with iconic performances and spectacular production design, continues to captivate audiences, ensuring its place as one of the most emotionally powerful and successful films of all time.",
            budget: "200M",
            revenue: "2.2B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'James Cameron',
            genre: 'Romance, Drama'
        },
        {
            id: 'm48',
            image: "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg",
            title: "Joker",
            year: 2019,
            duration: 122,
            link: "movie.html",
            review: "Joker offers a dark and gripping origin story of Gotham’s most notorious villain. Joaquin Phoenix’s Oscar-winning performance brings chilling depth and raw power to a character study about society’s failures and a descent into madness. It is haunting, uncomfortable, and unforgettable from beginning to end.",
            budget: "55M",
            revenue: "1.1B",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Todd Phillips',
            genre: 'Crime, Drama, Thriller'
        },
        {
            id: 'm49',
            image: "https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg",
            title: "Toy Story",
            year: 1995,
            duration: 81,
            link: "movie.html",
            review: "Toy Story is a groundbreaking animated film that charmed audiences with its lovable characters and imaginative tale of friendship. Pixar’s first feature film holds up with timeless storytelling and a heartfelt message about loyalty, growing up, and discovering one’s place in the world through the eyes of toys.",
            budget: "30M",
            revenue: "373M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'John Lasseter',
            genre: 'Animation, Adventure, Comedy'
        },
        {
            id: 'm50',
            image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Gladiator_%282000_film_poster%29.png/250px-Gladiator_%282000_film_poster%29.png",
            title: "Gladiator",
            year: 2000,
            duration: 155,
            link: "movie.html",
            review: "Gladiator revives the grandeur of classic historical epics with a story of betrayal, revenge, and honor. Russell Crowe’s Oscar-winning performance as Maximus, a fallen general turned gladiator, delivers a powerful and emotional journey through ancient Rome in a film filled with memorable action and stirring drama.",
            budget: "103M",
            revenue: "503M",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            director: 'Ridley Scott',
            genre: 'Action, Drama'
        }
    ],
    series: [
        {
            id: 's1',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiCtTwp9bSRc7VltVNvfhXkbJCS0Kc8b3jtA&s",
            title: "Game of Thrones",
            year: 2011,
            duration: 57,
            link: "series.html",
            review: "Game of Thrones set a new standard for fantasy series with its gritty realism, shocking plot twists, and enormous production scale. It captivated millions with its complex characters and layered political intrigue, though its finale divided audiences. Still, its legacy as a cultural phenomenon remains secure for years to come.",
            budget: "15M per episode",
            revenue: "3B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'David Benioff, D.B. Weiss',
            seasons: 8,
            genre:'Fantasy, Drama'
        },
        {
            id: 's2',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqhGRPHbiT9WRbp4Mc7kKgT6LHSPHrDiWfEg&s",
            title: "Breaking Bad",
            year: 2008,
            duration: 47,
            link: "series.html",
            review: "Breaking Bad transformed television storytelling with its deeply compelling portrait of Walter White, a chemistry teacher turned meth kingpin. Bryan Cranston’s iconic performance and the series’ slow-burn tension created one of the greatest antihero sagas ever. Its influence on modern prestige drama is still felt today.",
            budget: "3M per episode",
            revenue: "1B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Vince Gilligan',
            seasons: 5,
            genre: 'Crime, Drama, Thriller'
        },
        {
            id: 's3',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwPKlpSF1q_Gw4Txv9sjUoJFAYRsNgMqZGdw&s",
            title: "Stranger Things",
            year: 2016,
            duration: 51,
            link: "series.html",
            review: "Stranger Things blends supernatural horror, 80s nostalgia, and a tight-knit group of young friends to create a thrilling, heartfelt adventure. With memorable monsters, government conspiracies, and coming-of-age drama, the series became a global Netflix phenomenon, cementing its place in pop culture with an irresistible blend of mystery and charm.",
            budget: "12M per episode",
            revenue: "1B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'The Duffer Brothers',
            seasons: 4,
            genre: 'Sci-Fi, Horror, Drama'
        },
        {
            id: 's4',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw1-y3CidOjAoN7M9N5aioBr3V0l_3fTjGqg&s",
            title: "The Witcher",
            year: 2019,
            duration: 60,
            link: "series.html",
            review: "The Witcher brings sword-and-sorcery adventure to the screen with Henry Cavill’s charismatic Geralt battling monsters and destiny. Mixing political intrigue with monster-of-the-week thrills, the show adapted Andrzej Sapkowski’s novels with a gritty style and world-building that resonated with fans of fantasy looking for a new epic saga.",
            budget: "10M per episode",
            revenue: "500M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Lauren Schmidt Hissrich',
            seasons: 3,
            genre: 'Fantasy, Action, Adventure'
        },
        {
            id: 's5',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0luE8kykG2pZwOa3Hb25gnGEbYzfl4gCvuA&s",
            title: "The Mandalorian",
            year: 2019,
            duration: 42,
            link: "series.html",
            review: "The Mandalorian revitalized Star Wars on television with a Western-inspired story of a lone bounty hunter and the adorable Grogu. Jon Favreau’s vision captured the sense of adventure and mystique of the original trilogy, delivering weekly chapters that felt cinematic and earned loyal fans from all generations.",
            budget: "15M per episode",
            revenue: "2B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Jon Favreau',
            seasons: 3,
            genre: 'Sci-Fi, Action, Adventure'
        },
        {
            id: 's6',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCalhT36kvVsJb752WKHD-gOHjsJfzqVVfAA&s",
            title: "Sherlock",
            year: 2010,
            duration: 90,
            link: "series.html",
            review: "Sherlock modernized Arthur Conan Doyle’s legendary detective for a new era, with Benedict Cumberbatch and Martin Freeman delivering sharp, unforgettable performances. Its intricate plots, stylish visuals, and witty dialogue kept audiences guessing and turned the classic detective story into a global hit for a new generation of fans.",
            budget: "4M per episode",
            revenue: "500M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Steven Moffat, Mark Gatiss',
            seasons: 4,
            genre: 'Crime, Drama, Mystery'
        },
        {
            id: 's7',
            image: "https://resizing.flixster.com/aX9Yz5sNV2WpBA5CoENzIl9RbTM=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjI2NTU1OS53ZWJw",
            title: "The Crown",
            year: 2016,
            duration: 58,
            link: "series.html",
            review: "The Crown chronicles the reign of Queen Elizabeth II with stunning attention to historical detail, lavish costumes, and superb acting. It gives an intimate look at the human side of royalty, exploring personal sacrifices and political challenges, making it one of Netflix’s most acclaimed and prestigious original series ever produced.",
            budget: "13M per episode",
            revenue: "800M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Peter Morgan',
            seasons: 6, // Updated to current number of seasons
            genre: 'Drama, History'
        },
        {
            id: 's8',
            image: "https://m.media-amazon.com/images/M/MV5BYTVlZjNhYjktMWYyNy00MmYyLTk3ZjctMDQwMWIwYjdkODc3XkEyXkFqcGc@._V1_.jpg",
            title: "Dexter",
            year: 2006,
            duration: 53,
            link: "series.html",
            review: "Dexter offered a bold and twisted look at a serial killer who targets other criminals while balancing a normal life as a blood-splatter analyst. Michael C. Hall’s chilling performance and the show’s unique moral dilemmas made it a must-watch for fans of dark, psychological thrillers and edgy antiheroes.",
            budget: "2M per episode",
            revenue: "400M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'James Manos Jr.',
            seasons: 8, // Original series
            genre: 'Crime, Drama, Mystery'
        },
        {
            id: 's9',
            image: "https://m.media-amazon.com/images/M/MV5BNDdjNTEzMjMtYjM3Mi00NzQ3LWFlNWMtZjdmYWU3ZDkzMjk1XkEyXkFqcGc@._V1_.jpg",
            title: "Better Call Saul",
            year: 2015,
            duration: 46,
            link: "series.html",
            review: "Better Call Saul masterfully expands the Breaking Bad universe, following Jimmy McGill’s transformation into the slippery lawyer Saul Goodman. With intricate storytelling, dark humor, and layered performances, it stands as one of the best prequels in television history, showing tragedy, ambition, and moral decay in deeply human ways.",
            budget: "3M per episode",
            revenue: "300M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Vince Gilligan, Peter Gould',
            seasons: 6,
            genre: 'Crime, Drama'
        },
        {
            id: 's10',
            image: "https://m.media-amazon.com/images/M/MV5BMWJlN2U5MzItNjU4My00NTM2LWFjOWUtOWFiNjg3ZTMxZDY1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
            title: "The Boys",
            year: 2019,
            duration: 60,
            link: "series.html",
            review: "The Boys is a bold, subversive take on superheroes, exploring a world where powered individuals are corrupt and corporate-owned. Its dark humor, shocking violence, and biting social commentary give the show a distinctive, rebellious edge, delivering a unique twist on the genre and earning a passionate fan following worldwide.",
            budget: "10M per episode",
            revenue: "600M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Eric Kripke',
            seasons: 4, // Up to current
            genre: 'Action, Comedy, Drama'
        },        {
            id: 's11',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiCtTwp9bSRc7VltVNvfhXkbJCS0Kc8b3jtA&s",
            title: "Game of Thrones",
            year: 2011,
            duration: 57,
            link: "series.html",
            review: "Game of Thrones set a new standard for fantasy series with its gritty realism, shocking plot twists, and enormous production scale. It captivated millions with its complex characters and layered political intrigue, though its finale divided audiences. Still, its legacy as a cultural phenomenon remains secure for years to come.",
            budget: "15M per episode",
            revenue: "3B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'David Benioff, D.B. Weiss',
            seasons: 8,
            genre:'Fantasy, Drama'
        },
        {
            id: 's12',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqhGRPHbiT9WRbp4Mc7kKgT6LHSPHrDiWfEg&s",
            title: "Breaking Bad",
            year: 2008,
            duration: 47,
            link: "series.html",
            review: "Breaking Bad transformed television storytelling with its deeply compelling portrait of Walter White, a chemistry teacher turned meth kingpin. Bryan Cranston’s iconic performance and the series’ slow-burn tension created one of the greatest antihero sagas ever. Its influence on modern prestige drama is still felt today.",
            budget: "3M per episode",
            revenue: "1B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Vince Gilligan',
            seasons: 5,
            genre: 'Crime, Drama, Thriller'
        },
        {
            id: 's13',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwPKlpSF1q_Gw4Txv9sjUoJFAYRsNgMqZGdw&s",
            title: "Stranger Things",
            year: 2016,
            duration: 51,
            link: "series.html",
            review: "Stranger Things blends supernatural horror, 80s nostalgia, and a tight-knit group of young friends to create a thrilling, heartfelt adventure. With memorable monsters, government conspiracies, and coming-of-age drama, the series became a global Netflix phenomenon, cementing its place in pop culture with an irresistible blend of mystery and charm.",
            budget: "12M per episode",
            revenue: "1B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'The Duffer Brothers',
            seasons: 4,
            genre: 'Sci-Fi, Horror, Drama'
        },
        {
            id: 's14',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw1-y3CidOjAoN7M9N5aioBr3V0l_3fTjGqg&s",
            title: "The Witcher",
            year: 2019,
            duration: 60,
            link: "series.html",
            review: "The Witcher brings sword-and-sorcery adventure to the screen with Henry Cavill’s charismatic Geralt battling monsters and destiny. Mixing political intrigue with monster-of-the-week thrills, the show adapted Andrzej Sapkowski’s novels with a gritty style and world-building that resonated with fans of fantasy looking for a new epic saga.",
            budget: "10M per episode",
            revenue: "500M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Lauren Schmidt Hissrich',
            seasons: 3,
            genre: 'Fantasy, Action, Adventure'
        },
        {
            id: 's15',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0luE8kykG2pZwOa3Hb25gnGEbYzfl4gCvuA&s",
            title: "The Mandalorian",
            year: 2019,
            duration: 42,
            link: "series.html",
            review: "The Mandalorian revitalized Star Wars on television with a Western-inspired story of a lone bounty hunter and the adorable Grogu. Jon Favreau’s vision captured the sense of adventure and mystique of the original trilogy, delivering weekly chapters that felt cinematic and earned loyal fans from all generations.",
            budget: "15M per episode",
            revenue: "2B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Jon Favreau',
            seasons: 3,
            genre: 'Sci-Fi, Action, Adventure'
        },
        {
            id: 's16',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCalhT36kvVsJb752WKHD-gOHjsJfzqVVfAA&s",
            title: "Sherlock",
            year: 2010,
            duration: 90,
            link: "series.html",
            review: "Sherlock modernized Arthur Conan Doyle’s legendary detective for a new era, with Benedict Cumberbatch and Martin Freeman delivering sharp, unforgettable performances. Its intricate plots, stylish visuals, and witty dialogue kept audiences guessing and turned the classic detective story into a global hit for a new generation of fans.",
            budget: "4M per episode",
            revenue: "500M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Steven Moffat, Mark Gatiss',
            seasons: 4,
            genre: 'Crime, Drama, Mystery'
        },
        {
            id: 's17',
            image: "https://resizing.flixster.com/aX9Yz5sNV2WpBA5CoENzIl9RbTM=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjI2NTU1OS53ZWJw",
            title: "The Crown",
            year: 2016,
            duration: 58,
            link: "series.html",
            review: "The Crown chronicles the reign of Queen Elizabeth II with stunning attention to historical detail, lavish costumes, and superb acting. It gives an intimate look at the human side of royalty, exploring personal sacrifices and political challenges, making it one of Netflix’s most acclaimed and prestigious original series ever produced.",
            budget: "13M per episode",
            revenue: "800M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Peter Morgan',
            seasons: 6, // Updated to current number of seasons
            genre: 'Drama, History'
        },
        {
            id: 's18',
            image: "https://m.media-amazon.com/images/M/MV5BYTVlZjNhYjktMWYyNy00MmYyLTk3ZjctMDQwMWIwYjdkODc3XkEyXkFqcGc@._V1_.jpg",
            title: "Dexter",
            year: 2006,
            duration: 53,
            link: "series.html",
            review: "Dexter offered a bold and twisted look at a serial killer who targets other criminals while balancing a normal life as a blood-splatter analyst. Michael C. Hall’s chilling performance and the show’s unique moral dilemmas made it a must-watch for fans of dark, psychological thrillers and edgy antiheroes.",
            budget: "2M per episode",
            revenue: "400M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'James Manos Jr.',
            seasons: 8, // Original series
            genre: 'Crime, Drama, Mystery'
        },
        {
            id: 's19',
            image: "https://m.media-amazon.com/images/M/MV5BNDdjNTEzMjMtYjM3Mi00NzQ3LWFlNWMtZjdmYWU3ZDkzMjk1XkEyXkFqcGc@._V1_.jpg",
            title: "Better Call Saul",
            year: 2015,
            duration: 46,
            link: "series.html",
            review: "Better Call Saul masterfully expands the Breaking Bad universe, following Jimmy McGill’s transformation into the slippery lawyer Saul Goodman. With intricate storytelling, dark humor, and layered performances, it stands as one of the best prequels in television history, showing tragedy, ambition, and moral decay in deeply human ways.",
            budget: "3M per episode",
            revenue: "300M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Vince Gilligan, Peter Gould',
            seasons: 6,
            genre: 'Crime, Drama'
        },
        {
            id: 's20',
            image: "https://m.media-amazon.com/images/M/MV5BMWJlN2U5MzItNjU4My00NTM2LWFjOWUtOWFiNjg3ZTMxZDY1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
            title: "The Boys",
            year: 2019,
            duration: 60,
            link: "series.html",
            review: "The Boys is a bold, subversive take on superheroes, exploring a world where powered individuals are corrupt and corporate-owned. Its dark humor, shocking violence, and biting social commentary give the show a distinctive, rebellious edge, delivering a unique twist on the genre and earning a passionate fan following worldwide.",
            budget: "10M per episode",
            revenue: "600M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Eric Kripke',
            seasons: 4, // Up to current
            genre: 'Action, Comedy, Drama'
        },
                {
            id: 's21',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiCtTwp9bSRc7VltVNvfhXkbJCS0Kc8b3jtA&s",
            title: "Game of Thrones",
            year: 2011,
            duration: 57,
            link: "series.html",
            review: "Game of Thrones set a new standard for fantasy series with its gritty realism, shocking plot twists, and enormous production scale. It captivated millions with its complex characters and layered political intrigue, though its finale divided audiences. Still, its legacy as a cultural phenomenon remains secure for years to come.",
            budget: "15M per episode",
            revenue: "3B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'David Benioff, D.B. Weiss',
            seasons: 8,
            genre:'Fantasy, Drama'
        },
        {
            id: 's22',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqhGRPHbiT9WRbp4Mc7kKgT6LHSPHrDiWfEg&s",
            title: "Breaking Bad",
            year: 2008,
            duration: 47,
            link: "series.html",
            review: "Breaking Bad transformed television storytelling with its deeply compelling portrait of Walter White, a chemistry teacher turned meth kingpin. Bryan Cranston’s iconic performance and the series’ slow-burn tension created one of the greatest antihero sagas ever. Its influence on modern prestige drama is still felt today.",
            budget: "3M per episode",
            revenue: "1B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Vince Gilligan',
            seasons: 5,
            genre: 'Crime, Drama, Thriller'
        },
        {
            id: 's23',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwPKlpSF1q_Gw4Txv9sjUoJFAYRsNgMqZGdw&s",
            title: "Stranger Things",
            year: 2016,
            duration: 51,
            link: "series.html",
            review: "Stranger Things blends supernatural horror, 80s nostalgia, and a tight-knit group of young friends to create a thrilling, heartfelt adventure. With memorable monsters, government conspiracies, and coming-of-age drama, the series became a global Netflix phenomenon, cementing its place in pop culture with an irresistible blend of mystery and charm.",
            budget: "12M per episode",
            revenue: "1B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'The Duffer Brothers',
            seasons: 4,
            genre: 'Sci-Fi, Horror, Drama'
        },
        {
            id: 's24',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw1-y3CidOjAoN7M9N5aioBr3V0l_3fTjGqg&s",
            title: "The Witcher",
            year: 2019,
            duration: 60,
            link: "series.html",
            review: "The Witcher brings sword-and-sorcery adventure to the screen with Henry Cavill’s charismatic Geralt battling monsters and destiny. Mixing political intrigue with monster-of-the-week thrills, the show adapted Andrzej Sapkowski’s novels with a gritty style and world-building that resonated with fans of fantasy looking for a new epic saga.",
            budget: "10M per episode",
            revenue: "500M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Lauren Schmidt Hissrich',
            seasons: 3,
            genre: 'Fantasy, Action, Adventure'
        },
        {
            id: 's25',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0luE8kykG2pZwOa3Hb25gnGEbYzfl4gCvuA&s",
            title: "The Mandalorian",
            year: 2019,
            duration: 42,
            link: "series.html",
            review: "The Mandalorian revitalized Star Wars on television with a Western-inspired story of a lone bounty hunter and the adorable Grogu. Jon Favreau’s vision captured the sense of adventure and mystique of the original trilogy, delivering weekly chapters that felt cinematic and earned loyal fans from all generations.",
            budget: "15M per episode",
            revenue: "2B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Jon Favreau',
            seasons: 3,
            genre: 'Sci-Fi, Action, Adventure'
        },
        {
            id: 's26',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCalhT36kvVsJb752WKHD-gOHjsJfzqVVfAA&s",
            title: "Sherlock",
            year: 2010,
            duration: 90,
            link: "series.html",
            review: "Sherlock modernized Arthur Conan Doyle’s legendary detective for a new era, with Benedict Cumberbatch and Martin Freeman delivering sharp, unforgettable performances. Its intricate plots, stylish visuals, and witty dialogue kept audiences guessing and turned the classic detective story into a global hit for a new generation of fans.",
            budget: "4M per episode",
            revenue: "500M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Steven Moffat, Mark Gatiss',
            seasons: 4,
            genre: 'Crime, Drama, Mystery'
        },
        {
            id: 's27',
            image: "https://resizing.flixster.com/aX9Yz5sNV2WpBA5CoENzIl9RbTM=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjI2NTU1OS53ZWJw",
            title: "The Crown",
            year: 2016,
            duration: 58,
            link: "series.html",
            review: "The Crown chronicles the reign of Queen Elizabeth II with stunning attention to historical detail, lavish costumes, and superb acting. It gives an intimate look at the human side of royalty, exploring personal sacrifices and political challenges, making it one of Netflix’s most acclaimed and prestigious original series ever produced.",
            budget: "13M per episode",
            revenue: "800M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Peter Morgan',
            seasons: 6, // Updated to current number of seasons
            genre: 'Drama, History'
        },
        {
            id: 's28',
            image: "https://m.media-amazon.com/images/M/MV5BYTVlZjNhYjktMWYyNy00MmYyLTk3ZjctMDQwMWIwYjdkODc3XkEyXkFqcGc@._V1_.jpg",
            title: "Dexter",
            year: 2006,
            duration: 53,
            link: "series.html",
            review: "Dexter offered a bold and twisted look at a serial killer who targets other criminals while balancing a normal life as a blood-splatter analyst. Michael C. Hall’s chilling performance and the show’s unique moral dilemmas made it a must-watch for fans of dark, psychological thrillers and edgy antiheroes.",
            budget: "2M per episode",
            revenue: "400M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'James Manos Jr.',
            seasons: 8, // Original series
            genre: 'Crime, Drama, Mystery'
        },
        {
            id: 's29',
            image: "https://m.media-amazon.com/images/M/MV5BNDdjNTEzMjMtYjM3Mi00NzQ3LWFlNWMtZjdmYWU3ZDkzMjk1XkEyXkFqcGc@._V1_.jpg",
            title: "Better Call Saul",
            year: 2015,
            duration: 46,
            link: "series.html",
            review: "Better Call Saul masterfully expands the Breaking Bad universe, following Jimmy McGill’s transformation into the slippery lawyer Saul Goodman. With intricate storytelling, dark humor, and layered performances, it stands as one of the best prequels in television history, showing tragedy, ambition, and moral decay in deeply human ways.",
            budget: "3M per episode",
            revenue: "300M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Vince Gilligan, Peter Gould',
            seasons: 6,
            genre: 'Crime, Drama'
        },
        {
            id: 's30',
            image: "https://m.media-amazon.com/images/M/MV5BMWJlN2U5MzItNjU4My00NTM2LWFjOWUtOWFiNjg3ZTMxZDY1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
            title: "The Boys",
            year: 2019,
            duration: 60,
            link: "series.html",
            review: "The Boys is a bold, subversive take on superheroes, exploring a world where powered individuals are corrupt and corporate-owned. Its dark humor, shocking violence, and biting social commentary give the show a distinctive, rebellious edge, delivering a unique twist on the genre and earning a passionate fan following worldwide.",
            budget: "10M per episode",
            revenue: "600M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Eric Kripke',
            seasons: 4, // Up to current
            genre: 'Action, Comedy, Drama'
        },
                {
            id: 's31',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiCtTwp9bSRc7VltVNvfhXkbJCS0Kc8b3jtA&s",
            title: "Game of Thrones",
            year: 2011,
            duration: 57,
            link: "series.html",
            review: "Game of Thrones set a new standard for fantasy series with its gritty realism, shocking plot twists, and enormous production scale. It captivated millions with its complex characters and layered political intrigue, though its finale divided audiences. Still, its legacy as a cultural phenomenon remains secure for years to come.",
            budget: "15M per episode",
            revenue: "3B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'David Benioff, D.B. Weiss',
            seasons: 8,
            genre:'Fantasy, Drama'
        },
        {
            id: 's32',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqhGRPHbiT9WRbp4Mc7kKgT6LHSPHrDiWfEg&s",
            title: "Breaking Bad",
            year: 2008,
            duration: 47,
            link: "series.html",
            review: "Breaking Bad transformed television storytelling with its deeply compelling portrait of Walter White, a chemistry teacher turned meth kingpin. Bryan Cranston’s iconic performance and the series’ slow-burn tension created one of the greatest antihero sagas ever. Its influence on modern prestige drama is still felt today.",
            budget: "3M per episode",
            revenue: "1B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Vince Gilligan',
            seasons: 5,
            genre: 'Crime, Drama, Thriller'
        },
        {
            id: 's33',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwPKlpSF1q_Gw4Txv9sjUoJFAYRsNgMqZGdw&s",
            title: "Stranger Things",
            year: 2016,
            duration: 51,
            link: "series.html",
            review: "Stranger Things blends supernatural horror, 80s nostalgia, and a tight-knit group of young friends to create a thrilling, heartfelt adventure. With memorable monsters, government conspiracies, and coming-of-age drama, the series became a global Netflix phenomenon, cementing its place in pop culture with an irresistible blend of mystery and charm.",
            budget: "12M per episode",
            revenue: "1B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'The Duffer Brothers',
            seasons: 4,
            genre: 'Sci-Fi, Horror, Drama'
        },
        {
            id: 's34',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw1-y3CidOjAoN7M9N5aioBr3V0l_3fTjGqg&s",
            title: "The Witcher",
            year: 2019,
            duration: 60,
            link: "series.html",
            review: "The Witcher brings sword-and-sorcery adventure to the screen with Henry Cavill’s charismatic Geralt battling monsters and destiny. Mixing political intrigue with monster-of-the-week thrills, the show adapted Andrzej Sapkowski’s novels with a gritty style and world-building that resonated with fans of fantasy looking for a new epic saga.",
            budget: "10M per episode",
            revenue: "500M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Lauren Schmidt Hissrich',
            seasons: 3,
            genre: 'Fantasy, Action, Adventure'
        },
        {
            id: 's35',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0luE8kykG2pZwOa3Hb25gnGEbYzfl4gCvuA&s",
            title: "The Mandalorian",
            year: 2019,
            duration: 42,
            link: "series.html",
            review: "The Mandalorian revitalized Star Wars on television with a Western-inspired story of a lone bounty hunter and the adorable Grogu. Jon Favreau’s vision captured the sense of adventure and mystique of the original trilogy, delivering weekly chapters that felt cinematic and earned loyal fans from all generations.",
            budget: "15M per episode",
            revenue: "2B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Jon Favreau',
            seasons: 3,
            genre: 'Sci-Fi, Action, Adventure'
        },
        {
            id: 's36',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCalhT36kvVsJb752WKHD-gOHjsJfzqVVfAA&s",
            title: "Sherlock",
            year: 2010,
            duration: 90,
            link: "series.html",
            review: "Sherlock modernized Arthur Conan Doyle’s legendary detective for a new era, with Benedict Cumberbatch and Martin Freeman delivering sharp, unforgettable performances. Its intricate plots, stylish visuals, and witty dialogue kept audiences guessing and turned the classic detective story into a global hit for a new generation of fans.",
            budget: "4M per episode",
            revenue: "500M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Steven Moffat, Mark Gatiss',
            seasons: 4,
            genre: 'Crime, Drama, Mystery'
        },
        {
            id: 's37',
            image: "https://resizing.flixster.com/aX9Yz5sNV2WpBA5CoENzIl9RbTM=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjI2NTU1OS53ZWJw",
            title: "The Crown",
            year: 2016,
            duration: 58,
            link: "series.html",
            review: "The Crown chronicles the reign of Queen Elizabeth II with stunning attention to historical detail, lavish costumes, and superb acting. It gives an intimate look at the human side of royalty, exploring personal sacrifices and political challenges, making it one of Netflix’s most acclaimed and prestigious original series ever produced.",
            budget: "13M per episode",
            revenue: "800M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Peter Morgan',
            seasons: 6, // Updated to current number of seasons
            genre: 'Drama, History'
        },
        {
            id: 's38',
            image: "https://m.media-amazon.com/images/M/MV5BYTVlZjNhYjktMWYyNy00MmYyLTk3ZjctMDQwMWIwYjdkODc3XkEyXkFqcGc@._V1_.jpg",
            title: "Dexter",
            year: 2006,
            duration: 53,
            link: "series.html",
            review: "Dexter offered a bold and twisted look at a serial killer who targets other criminals while balancing a normal life as a blood-splatter analyst. Michael C. Hall’s chilling performance and the show’s unique moral dilemmas made it a must-watch for fans of dark, psychological thrillers and edgy antiheroes.",
            budget: "2M per episode",
            revenue: "400M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'James Manos Jr.',
            seasons: 8, // Original series
            genre: 'Crime, Drama, Mystery'
        },
        {
            id: 's39',
            image: "https://m.media-amazon.com/images/M/MV5BNDdjNTEzMjMtYjM3Mi00NzQ3LWFlNWMtZjdmYWU3ZDkzMjk1XkEyXkFqcGc@._V1_.jpg",
            title: "Better Call Saul",
            year: 2015,
            duration: 46,
            link: "series.html",
            review: "Better Call Saul masterfully expands the Breaking Bad universe, following Jimmy McGill’s transformation into the slippery lawyer Saul Goodman. With intricate storytelling, dark humor, and layered performances, it stands as one of the best prequels in television history, showing tragedy, ambition, and moral decay in deeply human ways.",
            budget: "3M per episode",
            revenue: "300M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Vince Gilligan, Peter Gould',
            seasons: 6,
            genre: 'Crime, Drama'
        },
        {
            id: 's40',
            image: "https://m.media-amazon.com/images/M/MV5BMWJlN2U5MzItNjU4My00NTM2LWFjOWUtOWFiNjg3ZTMxZDY1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
            title: "The Boys",
            year: 2019,
            duration: 60,
            link: "series.html",
            review: "The Boys is a bold, subversive take on superheroes, exploring a world where powered individuals are corrupt and corporate-owned. Its dark humor, shocking violence, and biting social commentary give the show a distinctive, rebellious edge, delivering a unique twist on the genre and earning a passionate fan following worldwide.",
            budget: "10M per episode",
            revenue: "600M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Eric Kripke',
            seasons: 4, // Up to current
            genre: 'Action, Comedy, Drama'
        },
                {
            id: 's41',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiCtTwp9bSRc7VltVNvfhXkbJCS0Kc8b3jtA&s",
            title: "Game of Thrones",
            year: 2011,
            duration: 57,
            link: "series.html",
            review: "Game of Thrones set a new standard for fantasy series with its gritty realism, shocking plot twists, and enormous production scale. It captivated millions with its complex characters and layered political intrigue, though its finale divided audiences. Still, its legacy as a cultural phenomenon remains secure for years to come.",
            budget: "15M per episode",
            revenue: "3B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'David Benioff, D.B. Weiss',
            seasons: 8,
            genre:'Fantasy, Drama'
        },
        {
            id: 's42',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqhGRPHbiT9WRbp4Mc7kKgT6LHSPHrDiWfEg&s",
            title: "Breaking Bad",
            year: 2008,
            duration: 47,
            link: "series.html",
            review: "Breaking Bad transformed television storytelling with its deeply compelling portrait of Walter White, a chemistry teacher turned meth kingpin. Bryan Cranston’s iconic performance and the series’ slow-burn tension created one of the greatest antihero sagas ever. Its influence on modern prestige drama is still felt today.",
            budget: "3M per episode",
            revenue: "1B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Vince Gilligan',
            seasons: 5,
            genre: 'Crime, Drama, Thriller'
        },
        {
            id: 's43',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwPKlpSF1q_Gw4Txv9sjUoJFAYRsNgMqZGdw&s",
            title: "Stranger Things",
            year: 2016,
            duration: 51,
            link: "series.html",
            review: "Stranger Things blends supernatural horror, 80s nostalgia, and a tight-knit group of young friends to create a thrilling, heartfelt adventure. With memorable monsters, government conspiracies, and coming-of-age drama, the series became a global Netflix phenomenon, cementing its place in pop culture with an irresistible blend of mystery and charm.",
            budget: "12M per episode",
            revenue: "1B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'The Duffer Brothers',
            seasons: 4,
            genre: 'Sci-Fi, Horror, Drama'
        },
        {
            id: 's44',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw1-y3CidOjAoN7M9N5aioBr3V0l_3fTjGqg&s",
            title: "The Witcher",
            year: 2019,
            duration: 60,
            link: "series.html",
            review: "The Witcher brings sword-and-sorcery adventure to the screen with Henry Cavill’s charismatic Geralt battling monsters and destiny. Mixing political intrigue with monster-of-the-week thrills, the show adapted Andrzej Sapkowski’s novels with a gritty style and world-building that resonated with fans of fantasy looking for a new epic saga.",
            budget: "10M per episode",
            revenue: "500M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Lauren Schmidt Hissrich',
            seasons: 3,
            genre: 'Fantasy, Action, Adventure'
        },
        {
            id: 's45',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0luE8kykG2pZwOa3Hb25gnGEbYzfl4gCvuA&s",
            title: "The Mandalorian",
            year: 2019,
            duration: 42,
            link: "series.html",
            review: "The Mandalorian revitalized Star Wars on television with a Western-inspired story of a lone bounty hunter and the adorable Grogu. Jon Favreau’s vision captured the sense of adventure and mystique of the original trilogy, delivering weekly chapters that felt cinematic and earned loyal fans from all generations.",
            budget: "15M per episode",
            revenue: "2B+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Jon Favreau',
            seasons: 3,
            genre: 'Sci-Fi, Action, Adventure'
        },
        {
            id: 's46',
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCalhT36kvVsJb752WKHD-gOHjsJfzqVVfAA&s",
            title: "Sherlock",
            year: 2010,
            duration: 90,
            link: "series.html",
            review: "Sherlock modernized Arthur Conan Doyle’s legendary detective for a new era, with Benedict Cumberbatch and Martin Freeman delivering sharp, unforgettable performances. Its intricate plots, stylish visuals, and witty dialogue kept audiences guessing and turned the classic detective story into a global hit for a new generation of fans.",
            budget: "4M per episode",
            revenue: "500M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Steven Moffat, Mark Gatiss',
            seasons: 4,
            genre: 'Crime, Drama, Mystery'
        },
        {
            id: 's47',
            image: "https://resizing.flixster.com/aX9Yz5sNV2WpBA5CoENzIl9RbTM=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjI2NTU1OS53ZWJw",
            title: "The Crown",
            year: 2016,
            duration: 58,
            link: "series.html",
            review: "The Crown chronicles the reign of Queen Elizabeth II with stunning attention to historical detail, lavish costumes, and superb acting. It gives an intimate look at the human side of royalty, exploring personal sacrifices and political challenges, making it one of Netflix’s most acclaimed and prestigious original series ever produced.",
            budget: "13M per episode",
            revenue: "800M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Peter Morgan',
            seasons: 6, // Updated to current number of seasons
            genre: 'Drama, History'
        },
        {
            id: 's48',
            image: "https://m.media-amazon.com/images/M/MV5BYTVlZjNhYjktMWYyNy00MmYyLTk3ZjctMDQwMWIwYjdkODc3XkEyXkFqcGc@._V1_.jpg",
            title: "Dexter",
            year: 2006,
            duration: 53,
            link: "series.html",
            review: "Dexter offered a bold and twisted look at a serial killer who targets other criminals while balancing a normal life as a blood-splatter analyst. Michael C. Hall’s chilling performance and the show’s unique moral dilemmas made it a must-watch for fans of dark, psychological thrillers and edgy antiheroes.",
            budget: "2M per episode",
            revenue: "400M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'James Manos Jr.',
            seasons: 8, // Original series
            genre: 'Crime, Drama, Mystery'
        },
        {
            id: 's49',
            image: "https://m.media-amazon.com/images/M/MV5BNDdjNTEzMjMtYjM3Mi00NzQ3LWFlNWMtZjdmYWU3ZDkzMjk1XkEyXkFqcGc@._V1_.jpg",
            title: "Better Call Saul",
            year: 2015,
            duration: 46,
            link: "series.html",
            review: "Better Call Saul masterfully expands the Breaking Bad universe, following Jimmy McGill’s transformation into the slippery lawyer Saul Goodman. With intricate storytelling, dark humor, and layered performances, it stands as one of the best prequels in television history, showing tragedy, ambition, and moral decay in deeply human ways.",
            budget: "3M per episode",
            revenue: "300M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Vince Gilligan, Peter Gould',
            seasons: 6,
            genre: 'Crime, Drama'
        },
        {
            id: 's50',
            image: "https://m.media-amazon.com/images/M/MV5BMWJlN2U5MzItNjU4My00NTM2LWFjOWUtOWFiNjg3ZTMxZDY1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
            title: "The Boys",
            year: 2019,
            duration: 60,
            link: "series.html",
            review: "The Boys is a bold, subversive take on superheroes, exploring a world where powered individuals are corrupt and corporate-owned. Its dark humor, shocking violence, and biting social commentary give the show a distinctive, rebellious edge, delivering a unique twist on the genre and earning a passionate fan following worldwide.",
            budget: "10M per episode",
            revenue: "600M+ franchise",
            watchlink: "#",
            "720pLink": "#",
            "1080pLink": "#",
            creator: 'Eric Kripke',
            seasons: 4, // Up to current
            genre: 'Action, Comedy, Drama'
        }
    ]
};